// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AuthSource string

const (
	AuthSourceLocal AuthSource = "local"
	AuthSourceLdap  AuthSource = "ldap"
)

func (e *AuthSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthSource(s)
	case string:
		*e = AuthSource(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthSource: %T", src)
	}
	return nil
}

type NullAuthSource struct {
	AuthSource AuthSource
	Valid      bool // Valid is true if AuthSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthSource) Scan(value interface{}) error {
	if value == nil {
		ns.AuthSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthSource), nil
}

type Methodology string

const (
	MethodologyPFD      Methodology = "PFD"
	MethodologyAIAG4    Methodology = "AIAG4"
	MethodologyAIAGVDA1 Methodology = "AIAGVDA1"
	MethodologyAPQP2    Methodology = "APQP2"
	MethodologyCP1      Methodology = "CP1"
)

func (e *Methodology) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Methodology(s)
	case string:
		*e = Methodology(s)
	default:
		return fmt.Errorf("unsupported scan type for Methodology: %T", src)
	}
	return nil
}

type NullMethodology struct {
	Methodology Methodology
	Valid       bool // Valid is true if Methodology is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMethodology) Scan(value interface{}) error {
	if value == nil {
		ns.Methodology, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Methodology.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMethodology) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Methodology), nil
}

type PackageKind string

const (
	PackageKindGeneral PackageKind = "general"
	PackageKindModel   PackageKind = "model"
)

func (e *PackageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PackageKind(s)
	case string:
		*e = PackageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PackageKind: %T", src)
	}
	return nil
}

type NullPackageKind struct {
	PackageKind PackageKind
	Valid       bool // Valid is true if PackageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPackageKind) Scan(value interface{}) error {
	if value == nil {
		ns.PackageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PackageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPackageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PackageKind), nil
}

type PackageStatus string

const (
	PackageStatusDraft      PackageStatus = "draft"
	PackageStatusInReview   PackageStatus = "in_review"
	PackageStatusApproved   PackageStatus = "approved"
	PackageStatusReleased   PackageStatus = "released"
	PackageStatusSuperseded PackageStatus = "superseded"
)

func (e *PackageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PackageStatus(s)
	case string:
		*e = PackageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PackageStatus: %T", src)
	}
	return nil
}

type NullPackageStatus struct {
	PackageStatus PackageStatus
	Valid         bool // Valid is true if PackageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPackageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PackageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PackageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPackageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PackageStatus), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleApprover UserRole = "approver"
	UserRoleReviewer UserRole = "reviewer"
	UserRoleAuthor   UserRole = "author"
	UserRoleViewer   UserRole = "viewer"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type User struct {
	ID           uuid.UUID
	Username     string
	DisplayName  string
	Email        *string
	Department   *string
	Role         UserRole
	AuthSource   AuthSource
	PasswordHash *string
	IsActive     bool
	LastLoginAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Version      int32
}
