// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: packages.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPackageByID = `-- name: GetPackageByID :one

SELECT id, kind, code, name, customer_id, part_id, pfmea_method, cp_format, status, revision,
       doc_seq, owner_id, plant, core_team, last_reviewed_at, content_version,
       created_at, updated_at, version
FROM packages
WHERE id = $1
`

type GetPackageByIDRow struct {
	ID             uuid.UUID
	Kind           PackageKind
	Code           string
	Name           string
	CustomerID     *uuid.UUID
	PartID         *uuid.UUID
	PfmeaMethod    Methodology
	CpFormat       Methodology
	Status         PackageStatus
	Revision       int32
	DocSeq         *int32
	OwnerID        uuid.UUID
	Plant          *string
	CoreTeam       *string
	LastReviewedAt time.Time
	ContentVersion int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Version        int32
}

// Query paket untuk sqlc (backend/internal/store/sqlc). Daftar lengkap dengan filter dan
// paginasi dibuat di M4.
func (q *Queries) GetPackageByID(ctx context.Context, id uuid.UUID) (GetPackageByIDRow, error) {
	row := q.db.QueryRow(ctx, getPackageByID, id)
	var i GetPackageByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Code,
		&i.Name,
		&i.CustomerID,
		&i.PartID,
		&i.PfmeaMethod,
		&i.CpFormat,
		&i.Status,
		&i.Revision,
		&i.DocSeq,
		&i.OwnerID,
		&i.Plant,
		&i.CoreTeam,
		&i.LastReviewedAt,
		&i.ContentVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listPackages = `-- name: ListPackages :many
SELECT id, kind, code, name, customer_id, part_id, status, revision, owner_id,
       content_version, updated_at, version
FROM packages
ORDER BY kind, code
`

type ListPackagesRow struct {
	ID             uuid.UUID
	Kind           PackageKind
	Code           string
	Name           string
	CustomerID     *uuid.UUID
	PartID         *uuid.UUID
	Status         PackageStatus
	Revision       int32
	OwnerID        uuid.UUID
	ContentVersion int64
	UpdatedAt      time.Time
	Version        int32
}

// Template General (kind general) tampil lebih dulu, lalu paket model urut kode.
func (q *Queries) ListPackages(ctx context.Context) ([]ListPackagesRow, error) {
	rows, err := q.db.Query(ctx, listPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPackagesRow
	for rows.Next() {
		var i ListPackagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Code,
			&i.Name,
			&i.CustomerID,
			&i.PartID,
			&i.Status,
			&i.Revision,
			&i.OwnerID,
			&i.ContentVersion,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
