// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, display_name, email, department, role, auth_source,
       is_active, last_login_at, created_at, updated_at, version
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Email       *string
	Department  *string
	Role        UserRole
	AuthSource  AuthSource
	IsActive    bool
	LastLoginAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Version     int32
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.AuthSource,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one

SELECT id, username, display_name, email, department, role, auth_source, password_hash,
       is_active, last_login_at, created_at, updated_at, version
FROM users
WHERE username = $1
`

// Query pengguna untuk sqlc (backend/internal/store/sqlc). Hash kata sandi hanya dibaca oleh
// GetUserByUsername (dipakai login mulai M2), tidak oleh daftar pengguna.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Email,
		&i.Department,
		&i.Role,
		&i.AuthSource,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, display_name, email, department, role, auth_source,
       is_active, last_login_at, version
FROM users
ORDER BY username
`

type ListUsersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	Email       *string
	Department  *string
	Role        UserRole
	AuthSource  AuthSource
	IsActive    bool
	LastLoginAt *time.Time
	Version     int32
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Email,
			&i.Department,
			&i.Role,
			&i.AuthSource,
			&i.IsActive,
			&i.LastLoginAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
